# Usa node:slim como imagen base, ya que node:alpine puede presentar problemas con algunas dependencias.
FROM node:22.13-slim AS builder

WORKDIR /app

# Copia el package.json y package-lock.json e instala las dependencias
COPY package.json package-lock.json ./
RUN npm install
    
# add app
COPY . ./
    
# Expone puerto 3000
EXPOSE 3000
    
# Lanza el front
CMD ["npm","start"]