name: Nginx pipeline

on:
  push:
    paths:
      - 'prueba3/index.html'
      
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:  
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.13.0
        with:
            file: Dockerfile
            context: ./prueba3
            push: true
            tags: user/app:latest
            
  deployement:
    runs-on: ubuntu-latest
    needs: docker_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy with Docker Compose
        working-directory: ./prueba3
        run: |
          docker-compose down
          docker-compose up -d
